name: CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/setup.yml
    steps:
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
