name: Deploy
on:
  push:
    branches:
      - main
jobs:
#  install:
#    name: Install
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Setup Node
#        uses: actions/setup-node@v2
#        with:
#          node-version: "18.x"
#      - name: Install Dependencies
#        run: npm install
#      - name: Build Application
#        run: npm run build
#  deploy-frontend:
#    name: Deploy
#    needs:
#      - install
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy
#        uses: crazy-max/ghaction-github-pages@v1
#        with:
#          target_branch: gh-pages
#          build_dir: dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/deploy-frontend
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
