name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-frontend:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Github Pages
        uses: ./.github/actions/deploy-frontend
        with:
          gh-token: ${{ secrets.REPO_TOKEN }}
